services:
  db:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    depends_on:
      - db
    build:
      context: ..
      dockerfile: docker/Dockerfile.web
      args:
        - DATABASE_URL=${DATABASE_URL}
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "3001:3001"
      
  backend:
    depends_on:
      - db
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "3000:3000"

  ws:
    depends_on:
      - db
    build:
      context: ..
      dockerfile: docker/Dockerfile.ws
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "3002:3002"

volumes:
  postgres_data:   





 