FROM oven/bun:latest

WORKDIR /app

ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./docker/entrypoint-web.sh /entrypoint.sh

COPY ./apps/web/package.json ./apps/web/package.json

RUN bun install

COPY ./apps/web ./apps/web

RUN cd packages/db && bunx prisma generate && cd ../..

RUN echo DATABASE_URL=${DATABASE_URL} >> apps/web/.env

RUN bun run build --filter=web

RUN rm apps/web/.env

EXPOSE 3001

RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["bun", "run", "start", "--filter=web"]