FROM oven/bun:latest

WORKDIR /app

ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/web/package.json ./apps/web/package.json

RUN bun install

COPY ./apps/web ./apps/web

RUN cd packages/db && bunx prisma generate && cd ../..

RUN DATABASE_URL=${DATABASE_URL} bun run build --filter=web

EXPOSE 3001

CMD ["bun", "run", "start", "--filter=web"]