name: deploy frontend

on: 
  push:
    branches:
      - main

jobs:
  deploy-everything:
    runs-on: ubuntu-latest

    steps:


      # - name: checkout repository
      #   uses: actions/checkout@v4

      # - name: Setup Bun
      #   uses: oven-sh/setup-bun@v1
      #   with:
      #     bun-version: latest

      # - name: install dependecies
      #   run: bun install 

      # - name: build the project
      #   env:
      #     DATABASE_URL: ${{ secrets.DATABASE_URL }}
      #   run: bun run build --filter=web

    #   - name: deploy to server
    #     uses: appleboy/ssh-action@v1.2.0
    #     with:
    #       host: ${{secrets.HOST}}
    #       username: ${{secrets.USER}}
    #       key: ${{secrets.SSH_KEY}}
    #       script: |
    #         cd ~/turbo-app-fe
    #         git pull origin main
    #         rm -r /apps/backend /apps/ws
    #         cd packages/db && bunx prisma generate && cd ../..
    #         bun install
    #         cd app/web
    #         bun run build
    #         export DATABASE_URL=${{secrets.DATABASE_URL}}
    #         pm2 restart turbo-app-fe --update-env || pm2 start "bun run start" --name=turbo-app-fe 


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: docker build and push
        uses: docker/build-push-action@v6
        with:
            context: .
            file: docker/Dockerfile.web
            push: true
            cache-from: type=registry,ref=prasadev/turbo-web-app:buildcache                        #this will use cached image layers while building image
            cache-to: type=registry,ref=prasadev/turbo-web-app:buildcache,mode=max                #this will cache new layers (max means cache maximum layers)
            build-args: |
              DATABASE_URL=${{secrets.DATABASE_URL}}
            tags: prasadev/turbo-web-app:latest   

      - name: deploy    
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USER}}
          key: ${{secrets.SSH_KEY}}   
          script: |
            sudo docker pull prasadev/turbo-web-app:latest
            sudo docker stop web-app || true
            sudo docker rm web-app || true
            sudo docker run -d \
              -p 80:3001 \
              --env DATABASE_URL="${{secrets.DATABASE_URL}}"
              --name web-app \
              --restart unless-stopped \
              prasadev/turbo-web-app:latest



      